# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: "24.1.1"
  hooks:
  - id: black

- repo: https://github.com/PyCQA/bandit
  rev: "1.7.7"
  hooks:
  - id: bandit
    exclude: "^tests/"

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
      - "-rn" # Only display messages
      - "-sn" # Don't display the score
      - "--exit-zero"
      - "--fail-on=\"F,E,W\""

    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]

- repo: https://github.com/python-poetry/poetry
  rev: "1.7.1"
  hooks:
  - id: poetry-check
  - id: poetry-lock
  - id: poetry-export
    args:
    - "--format=requirements.txt"
    - "--output=requirements.txt"
  - id: poetry-export
    args:
    - "--format=requirements.txt"
    - "--with=dev"
    - "--output=requirements.dev.txt"
