[tool.poetry]
name = "cellophane"
version = "0.0.2"
description = "Library for wrappers integrating with SLIMS"
authors = ["Erik Demitz-Helin <erik.demitz-helin@gu.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
slims-python-api = {version = "^6.8.0", source = "pypi"}
click = "^8.1.3"
psutil = "^5.9.4"
rich-click = {version = "^1.6.0", source = "pypi"}
uge-drmaa2 = {git = "https://github.com/gridengine/drmaa2-python.git", branch = "v8.7.4"}
humanfriendly = "^10.0"
jsonschema = "^4.17.3"
pyaml = "^21.10.1"
attrs = "^23.1.0"


[tool.poetry.group.dev.dependencies]
pylint = "^2.15.10"
mypy = "^0.991"
bandit = "^1.7.4"
types-pyyaml = "^6.0.12.2"
black = "^22.12.0"
pyright = "^1.1.288"
flake8 = "^6.0.0"
ipdb = "^0.13.13"
gitpython = "^3.1.31"
questionary = "^1.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
