---
name: Run pytest

permissions:
  checks: write
  pull-requests: write

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      head:
        required: true
        type: string
      pr-head-sha:
        required: true
        type: string
      publish-results:
        type: boolean
        default: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head }}
      - uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
      - name: rye-sync
        run: rye sync
      - name: pytest
        env:
          TERM: dumb
          COLUMNS: 500
          TERMINAL_WIDTH: 500
        run: TERMINAL_WIDTH=500 rye run pytest --junit-xml=pytest.xml
      - uses: actions/upload-artifact@v4
        if: (!cancelled())
        with:
          name: pytest.xml
          path: pytest.xml
          retention-days: 1
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled() && inputs.publish-results)
        with:
          files: pytest.xml
          commit: ${{ inputs.pr-head-sha }}
