# Move non-release PRs to dev branch
---
name: PR Update

permissions: read-all

on: # yamllint disable-line rule:truthy
  workflow_run:
    workflows:
    - PR Opened/Edit/Reopened on Main
    - PR Opened/Edit/Reopened on Dev
    types: [completed]

concurrency:
  group: ${{ github.workflow }}

jobs:
  publish-pytest-results:
    name: Publish pytest results
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: dawidd6/action-download-artifact@v7
        with:
          name: pytest.xml
          run_id: ${{ github.event.workflow_run.id }}
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: pytest.xml
          commit: ${{ github.event.workflow_run.head_sha }}
