# Create a draft release
---
  on:
    workflow_call:
      inputs:
        event_name:
          type: string
          description: Original event name
          required: true
      outputs:
        tag_name:
          description: The tag name of the release
          value: ${{ jobs.update_release_draft.outputs.tag_name }}

  jobs:
    update_release_draft:
      name: Update release draft
      permissions:
        contents: write
        pull-requests: write
      runs-on: ubuntu-latest
      outputs:
        tag_name: ${{ steps.draft_release.outputs.tag_name }}
      steps:
        - uses: release-drafter/release-drafter@v5
          id: draft_release
          env:
            GITHUB_TOKEN: ${{ github.token }}
