# Main CI workflow
---
  on:
    push:
      branches: [main, dev]
    pull_request:
      types: [opened, reopened, synchronize]
      branches: [main, dev]

  permissions: read-all

  jobs:
    lint:
      name: Lint Codebase
      uses: ./.github/workflows/mega-linter.yml
      permissions:
        contents: write
        issues: write
        pull-requests: write
        statuses: write
      with:
        event_name: ${{ github.event_name }}
    test:
      name: Run Tests
      uses: ./.github/workflows/pytest.yml
      permissions:
        checks: write
        pull-requests: write
    draft_release:
      name: Draft Release
      if: ${{ github.ref_name == 'main' }}
      uses: ./.github/workflows/release-drafter.yml
      permissions:
        contents: write
        pull-requests: write
      with:
        event_name: ${{ github.event_name }}
    bump_version:
      name: Bump Version
      needs: draft_release
      if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
      uses: ./.github/workflows/poetry-version.yml
      permissions:
        contents: write
      with:
        version: ${{ needs.draft_release.outputs.tag_name }}
